name: Run a test

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
 build:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v4
       with:
         # Make sure the release step uses its own credentials.
         persist-credentials: false
         
     - name: Setup Node.js
       id: setup-node
       uses: actions/setup-node@v4
       with:
         node-version-file: .node-version
         cache: npm
         
     - run: |
         npm ci
         npm run all

     - name: Run semantic-release
       # This process will run `ncc`, commit files, push a Git commit, and release to GitHub and npmjs.
       run: |
         npx semantic-release
       env:
         GITHUB_TOKEN: ${{ secrets.PAT_TO_PUSH }}
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

 test:
    needs: build
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v4

     - name: Inno Setup Action
       uses: ./
       with:
         path: scripts/test.iss
         options: /O+
